version = 1
SPDX-PackageName = "dde-session"
SPDX-PackageSupplier = "UnionTech Software Technology Co., Ltd. <>"
SPDX-PackageDownloadLocation = "https://github.com/linuxdeepin/dde-session"

[[annotations]]
path = ["README.md", "README.zh_CN.md", "CHANGELOG.md", "docs/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["**.pro", "**.prf", "**.pri", "**CMakeLists.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "dbus/**.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = ["dbus/**.service", "systemd/**", "tools/**.service", "tools/dde-login-reminder/translations/**.ts"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = [".github/**", ".gitlab-ci.yml", ".obs/workflows.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["src/**.xml", ".clog.toml", "configs/**.json", "src/**conf", "**.sh", "src/**.yaml", ".tx/config", ".tx/transifex.yaml", "tools/dde-login-reminder/dde-login-reminder.desktop"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["rpm/**", "debian/**", "archlinux/**", "misc/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "toolGenerate/**/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
